blank_issues_enabled: false
contact_links:
  - name: Discussions Forum
    url: https://github.com/marcelhaindl/imgsort/discussions
    about: Questions and configuration or deployment problems can also be discussed.
